### ISSUE TITLE
add Kyle as maintainer

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#79]

**Comment by neffmallon** [comment]
So do we close this issue now that it is fixed in development or do we wait until the development branched is merged into the master branch?

**Comment by ksunden** [comment]
We wait until it is in master, This is so that there it is still visible to users what known issues still exist in master. As such, we have added the `fixed in development` label, which indicates that no further action is needed

**Comment by untzag** [comment]
consider adding `-label:"fixed in development" ` into your issue filters to hide this flavor of issue
